### ISSUE TITLE
Unused texts?

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon#36] opened 2022-05-25 15:14 UTC
NPC_texts.amb - sub-file 0x36 (54)

prophesore wrote that the following NPC events of character "Brog" seem to have no event trigger

1. "YOU KNOW ABOUT MY LOVE FOR MAGIC. WHAT A SHAME THAT SO FEW OF THE PEOPLE HERE FEEL THE SAME!"
2. "HOW HAPPY I WOULD BE IF DORINA RETURNED TO US!"
3. "MY FRIENDS, MY PLEASURE ABOUT DORINA RETURNING TO US IS AT LEAST AS GREAT AS KIRE'S! AND HOW SHE HAS DEVELOPED HER TALENTS! TREMENDOUSLY WELL! AS I HEARD, YOU HAD A FEW PROBLEMS BECAUSE OF THAT ..."

@Pyrdacor investigated and said the 3 strings cannot be triggered in the current state of the game data.

1. This text should be used when you say the word "MAGIC" and global variable 48 would be 1.
2. This text should be used when you say the word "DORINA" and global variable 49 would be 1 and Dorina has **not** received Kire's letter.
3. This text should be used when you say the word "DORINA" and global variable 49 would be 1 and Dorina has received Kire's letter.

The problem now is that there are no events in the entire game which set either global variable 48 or 49 to 1.

From the context of the texts that are used when those variables are not set, I am sure that these variables should be set by the Brog events themselves.

**Comment by Pyrdacor** [comment] 2022-07-01 14:28
Ok I had a closer look.

Both variables are "have already talked about" switches. So they should be set after the first text was triggered once. So if you said "MAGIC" and read the first message, the variable 48 is set so the next use of "MAGIC" will show the second message. The same is true for "DORINA". I will add those two variable setters now.

There are also two more bugs (in both languages). When you say "DOR KIREDON" Brog says:

```
"YES, THE TOWN OF OUR FRIENDS OF NATURE. MY BROTHER IS THERE NOW AND IS RESEARCHING THE HEALING FORCES OF THE LOCAL FLORA."
```

But actually this is Dor Grestin and not Dor Kiredon. From context Dor Grestin is right here and it also has an entry in the dictionary. So I will change that too so that you have to say "DOR GRESTIN" to trigger the message.

The second bug is that when you say "DORINA" for the first time, he says that his brother the healer went to Dor Kiredon. Of course Asrub is meant and he is gone to Dor Grestin of course as well. So I will adjust the text as well. Then the Brog NPC should be working as intended.

Will be part of 1.15.

**Comment by Pyrdacor** [comment] 2022-07-01 16:07
1.15 is now released ;)

**Closed by Pyrdacor** 2022-07-01 16:07 UTC
Labels: enhancement
