### ISSUE TITLE
THE OS HAS RUN OUT OF MEMORY (and link to PARTY_DATA.SAV)

### ISSUE THREAD

**Issue by kempynezumi** [Pyrdacor/Ambermoon#9] opened 2021-08-18 21:05 UTC
THE OS HAS RUN OUT OF MEMORY (and link to PARTY_DATA.SAV)

Such error after choosing and confirming character (starting new game). 1.08 from ambermoon_english_1.08_extracted.lha. Real amiga, apollo 040, 2mb chip, 32mb fast, kick 31 (mapped), classicwb

**Comment by Pyrdacor** [comment] 2021-08-18 21:09
Does it work with 1.07?

**Comment by kempynezumi** [comment] 2021-08-18 21:25
I've just downloaded 1.07 extracted from there: https://github.com/Pyrdacor/Ambermoon/tree/master/Disks/English

And same error. Also tried to run both versions directly from ram: and got "disk is full" error at same moment (and also link to party_data.sav) with over 20mb of free memory.

**Comment by Pyrdacor** [comment] 2021-08-18 21:32
@a1exh Do you have an idea what could be the cause?

**Comment by kempynezumi** [comment] 2021-08-18 21:36
Have to add that party_char.amb is modified by program (it keeps changed name every time i try to run). Other files in save.00 directory are untouched.

**Comment by Pyrdacor** [comment] 2021-08-18 21:40
Can you try with a untouched Party_char.amb?

**Comment by kempynezumi** [comment] 2021-08-18 22:20
If i unpack whole archive (1.07 or 1.08), and then go into new game, and then click ok at character screen without any changes, game starts. But new problem appeared - when i try to save game (in both 1.07 or 1.08) a got error "can't find file party_data.sav". But this file exists. ;/

**Comment by Pyrdacor** [comment] 2021-08-19 00:29
Can you copy the folder Save.00 ten times and rename them to Save.01 up to Save.10. Saving should work then.

**Comment by Pyrdacor** [comment] 2021-08-19 00:39
I added a note about it in the GitHub readme just now.

**Comment by a1exh** [comment] 2021-08-19 06:36
> @a1exh Do you have an idea what could be the cause?

Hmmm what disk file system do you have? Perhaps Ambermoon only works with FFS? I've only ever used FFS. I've never tried PFS3 or AFS

**Comment by kempynezumi** [comment] 2021-08-19 19:12
I've created and copied all save slots and now games starts and i am able to save/load. Still can't change name/avatar becasue if i do this game won't start and also i won't be able to even use "continue". So at this point i'm stick to young Thalion guy. 

Tested in both 1.07 and 1.08 downloaded from GitHub here.

**Comment by kempynezumi** [comment] 2021-08-19 19:32
@a1exh 
Hmmm what disk file system do you have? Perhaps Ambermoon only works with FFS? I've only ever used FFS. I've never tried PFS3 or AFS

Yes, i'm using PFS3. I was also warned yesterday from other source that there may be some problems with PFS3 and Ambermoon. Sadly don't have any FFS formatted bootable CF to test.

**Comment by a1exh** [comment] 2021-08-20 00:22
I deleted my reply because I re-read and I thought you were trying to run from RAM:?

I've got a niggling feeling Ambermoon doesn't work with anything other than FFS but I could be wrong. I thought it was OS legal but not 100% sure.

If in doubt try the WHDload slave for it? I personally don't use it as I've never experienced any issues with the HDD installer which came with the game.

**Comment by kempynezumi** [comment] 2021-08-20 20:54
I've tried Ambermoon WHDLoad slave 2.0 with 1.07 and it works ok. No errors when i try to change name or avatar. Continue, Saving/Loading is ok, even if saving is much longer. 

Then i unpacked and replaced files with 1.08 patch and it seems it works as well. Need to play more to be sure.

**Comment by a1exh** [comment] 2021-08-20 21:39
@kempynezumi do you think that implies that built in Ambermoon HDD routines only work with FFS partitions?

**Comment by kempynezumi** [comment] 2021-08-20 22:11
To be 100% sure i need to test this specific archive/version on my configuration on ffs partition.

**Comment by kempynezumi** [comment] 2021-08-24 14:07
I've found my old CD with copy of installed Ambermoon i was playing 22 years ago (files has datestamp july 1999). That was version from MA CD, 1.07. Archive includes also some of my save games (entering Newlake for the first time). For my surprise, everything works fine on my PFS. I can easily save/load or star new game and change avatar/name of my hero. No errors yet. 

I need to overwrite files from 1.08 patch archive only and will report what will happen.

**Comment by Pyrdacor** [comment] 2021-08-31 10:02
Can you try the ADF disk images for 1.09 from here: https://github.com/Pyrdacor/Ambermoon/raw/master/Disks/English/ambermoon_english_1.09_adf.lha

Maybe you can install it to the HD this way.

**Comment by Pyrdacor** [comment] 2021-09-01 20:24
The 1.08 and 1.09 versions included a patch from meynaf. Maybe he changed something with the main assemblies (@a1exh)?

**Comment by a1exh** [comment] 2021-09-02 07:19
I believe that Meynaf's patches didn't change anything WRT the executables. Just data. 

@kempynezumi are you still using the WHDload installation? Or a new installation using the installer on the v1.09 disks?

**Comment by a1exh** [comment] 2021-09-02 07:41
The DE version of Ambermoon had issues with 040 and data caches and an official v1.05 release was done. You could get this file from the Aminet. 

http://aminet.net/package/game/patch/amber

But I am sure this fix was prior to the assembly/compilation of the v1.07 exe and so v1.07 already includes this fix.

**Comment by a1exh** [comment] 2021-09-02 08:21
There are hints around the net that switching off VBR-to-FAST can improve the stability of Ambermoon. The WHDload install says it had to fix this. I've never had this issue but worth a go.

**Comment by Pyrdacor** [comment] 2021-09-12 21:24
@kempynezumi Maybe this is related to #15. Please use the updated files from the bugfix folder mentioned there. I will provide a fixed full version of 1.10 soon.

You will need the *_text.amb files only on top of 1.10 or 1.09.

**Comment by nicodex** [comment] 2021-09-16 06:04
> Maybe this is related to #15.

I don't think that this is related. The game is very OS friendly and only uses official library calls. Therefore the file system doesn't really matter. In fact, the game has been developed with OFS and [FFS](https://gitlab.com/ambermoon/research/-/blob/master/data/dh/v101-1993-10-22-german/Amberfiles/Trouble.doc#L45) in mind and only uses DOS calls (agnostic to the file system that is assigned to the device).

The latest version also supports moved m68k vector tables (the VBR base address is read during the initialization).

I expect the main problem to be the many global/static variables that hold the game state/content/references. However, back in the days, like self-modifying code, this used to be a very common practice. The problems later appeared with CPUs that supported code and / or data caches - something that isn't easy to solve in retrospect.

**Comment by Pyrdacor** [comment] 2021-09-16 10:33
Ok thanks for clarification. I will close this for now. If there is still something to do, just let me know.

**Closed by Pyrdacor** 2021-09-16 10:33 UTC
