### ISSUE TITLE
[Bug report] wrong scroll name

### ISSUE THREAD

**Issue by wereant** [Pyrdacor/Ambermoon#31] opened 2022-04-14 20:14 UTC
Scroll named Flight should be named Escape, since it contains this spell (escape from battle), not flight.

**Comment by a1exh** [comment] 2022-04-15 15:30
The naming is correct if probably a poor translation and a little ambiguous. "Flight" in English can mean to 'run away". It does not have to mean Fly as in the air

**Comment by Pyrdacor** [comment] 2022-04-15 15:42
I think the problem is that in general the spells have the same names as the scrolls but in this case the scroll's name is "Flight" while the spell is called "Escape".

**Comment by Pyrdacor** [comment] 2022-04-15 15:44
What would be the better name? I would pick it for both then.

**Comment by a1exh** [comment] 2022-04-15 20:22
Traditionally in these situations I've looked at the German and tried to find a better translation

**Comment by wereant** [comment] 2022-04-15 20:56
I would pick Escape, since it describes spell in the scroll in less ambiguous manner.

**Comment by Pyrdacor** [comment] 2022-04-15 23:39
In German it is "Flucht" which is the act of fleeing or the state where you successfully fled.

I would also choose "Escape" here as it sounds much more fitting. But as a non-native speaker I can't really tell. Sometimes some words emphasize something or are used in older language which would fit to the fantasy genre, etc.

**Comment by a1exh** [comment] 2022-04-16 07:51
To me "Flee" and "Flee from battle" are better English than "Escape" and "Escape from battle". The former is submissive, implies retreat, panic whereas the latter could be seen as dominant imply tactical, withdrawal, evasion. However they are both acceptable. As long as both are consistent I don't think it matters.

**Comment by Pyrdacor** [comment] 2022-04-22 17:43
Now that you put it that way I also tend more towards "Flight".

**Comment by Pyrdacor** [comment] 2022-05-13 10:49
Spell and scroll now are called "Flight". Will be part of 1.14.

**Closed by Pyrdacor** 2022-05-13 10:49 UTC
Labels: bug
